.TH xt_asn_dl 1 "2017-08-06" "xtables-addons" "xtables-addons"
.SH Name
.PP
xt_asn_dl \(em download ASN database files
.SH Syntax
.PP
\fI/usr/libexec/xt_asn/\fP\fBxt_asn_dl\fP
.SH Description
.PP
Downloads and unpacks the ASN map from BGP and convert to MaxMind format databases for IPv4 and
IPv6 and unpacks them to the current directory.
.PP
Since the script is usually installed to the libexec directory of the
xtables-addons package and this is outside $PATH (on purpose), invoking the
script requires it to be called with a path.
.SH Options
.PP
None.
.SH See also
.PP
xt_asn_build(1)
