#!/bin/sh

# Install Net Netmask
wget http://search.cpan.org/CPAN/authors/id/M/MU/MUIR/modules/Net-Netmask-1.9022.tar.gz
tar -xf Net-Netmask-1.9022.tar.gz
cd Net-Netmask-1.9022
perl Makefile.PL
make&&make test
make install
cd ..
# Install Net IP
wget http://search.cpan.org/CPAN/authors/id/M/MA/MANU/Net-IP-1.26.tar.gz
tar -xf Net-IP-1.26.tar.gz
cd Net-IP-1.26
perl Makefile.PL
make&&make test
make install
cd ..

# remove old BGP DB
rm -f ./asn.csv
# Create dir
#mkdir /opt/bgp
# http://phpsuxx.blogspot.com/2011/12/full-bgp.html
yesterday_date=$(date --date='1 days ago' '+%Y.%m')
yesterday_date_with_day=$(date --date='1 days ago' '+%Y%m%d')
# get routing data for yesterday at 5 o'clock 
wget http://archive.routeviews.org/bgpdata/${yesterday_date}/RIBS/rib.${yesterday_date_with_day}.0600.bz2 -O ./rib.bz2
# Convert to Max Mind Format.
echo "Star converting... (it will take 15-30 minutes)"
/usr/local/bin/bgpdump ./rib.bz2 | ./bgp_table_to_text.pl > ./asn.csv

# Install
./xt_asn_build -D /usr/share/xt_asn asn.csv